use usermeta;
delete from boostconfig where accboostconfigid="z-darwin-defaultboostconfig" and columnname like "companyName%";
INSERT INTO boostconfig VALUES ('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyName','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyName','former','former1BusinessNameWithStemmer',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyName','gdmi','businessNameWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyName','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyName','gdmi','ceoName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyName','gdmi','tradestyle1',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameWP','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameWP','former','former1BusinessNameWithStemmer',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameWP','gdmi','businessNameWPWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameWP','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameWP','gdmi','ceoNameWP',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameWP','gdmi','tradestyle1',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','former','former1BusinessNameWithStemmer',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','gdmi','businessNameWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','gdmi','ceoName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','gdmi','tradestyle1',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShort','tags','shortBusinessName',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','former','former1BusinessNameWithStemmer',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','gdmi','businessNameWPWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','gdmi','ceoNameWP',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','gdmi','tradestyle1',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWP','tags','shortBusinessNameWithStopWordsWP',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','former','former1AcronymBusinessName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','gdmi','businessNameWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','gdmi','businessNameWithNGrams',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','gdmi','ceoName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyle1',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcro','tags','acronymBusinessName',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','former','former1AcronymBusinessName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','gdmi','businessNameWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','gdmi','businessNameWithNGrams',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','gdmi','ceoName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyle1',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithAcroWP','tags','acronymBusinessName',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','former','former1BusinessNameWithStemmer',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','gdmi','businessNameWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','gdmi','ceoName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyle1',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWords','tags','shortBusinessNameWithStopWords',2),

								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','eha','fullName',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','former','former1BusinessNameWithStemmer',1),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','businessNameWPWithStemmer',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','businessName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','ceoName',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyle1',2),
								('z-darwin-defaultboostconfig','firstpassMapping','search_companies','companyNameShortWithStopWordsWP','tags','shortBusinessNameWithStopWordsWP',2);								

delete from secondaryboostconfig where boostprofileid="secondPassMapping" and columnname like "companyName%";
INSERT INTO secondaryboostconfig VALUES ('secondPassMapping','search_companies','companyName','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyName','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyName','former','former3BusinessName',1),
										('secondPassMapping','search_companies','companyName','gdmi','businessNameWithNGrams',2),
										('secondPassMapping','search_companies','companyName','gdmi','businessName',2),
										('secondPassMapping','search_companies','companyName','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyName','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyName','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyName','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyName','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyName','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameWP','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameWP','former','former2BusinessName',1),
										('secondPassMapping','search_companies','companyNameWP','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameWP','former','former3BusinessName',1),
										('secondPassMapping','search_companies','companyNameWP','gdmi','businessNameWPWithNGrams',2),
										('secondPassMapping','search_companies','companyNameWP','gdmi','businessNameWP',2),
										('secondPassMapping','search_companies','companyNameWP','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameWP','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameWP','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameWP','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameWP','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameWP','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameShort','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShort','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShort','gdmi','businessNameWithNGrams',2),
										('secondPassMapping','search_companies','companyNameShort','gdmi','businessName',2),
										('secondPassMapping','search_companies','companyNameShort','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameShort','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameShort','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameShort','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameShort','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameShort','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameShortWP','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWP','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','businessNameWPWithNGrams',2),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','businessNameWP',2),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameShortWP','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameShortWithAcro','former','former2AcronymBusinessName',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','former','former3AcronymBusinessName',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','businessNameWithNGrams',2),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','businessName',2),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameShortWithAcro','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameShortWithAcroWP','former','former2AcronymBusinessName',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','former','former3AcronymBusinessName',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','businessNameWPWithNGrams',2),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','businessName',2),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameShortWithAcroWP','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameShortWithStopWords','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','businessNameWithNGrams',2),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','businessName',2),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWords','gdmi','tradestyleName2',1),

										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','former','former2BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','former','former3BusinessNameWithStemmer',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','businessNameWPWithNGrams',2),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','businessName',2),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyle2',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyle3',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyle4',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyle5',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyleName',1),
										('secondPassMapping','search_companies','companyNameShortWithStopWordsWP','gdmi','tradestyleName2',1);
										
delete from boostconfigtemplate where boostprofileid="countryNameDomainOnlyMapping";
insert into boostconfigtemplate values("countryNameDomainOnlyMapping","search_companies","companyName","gdmi","businessNameWithStemmer",2.0),
                                      ("countryNameDomainOnlyMapping","search_companies","companyName","gdmi","businessName",1.0),
                                      ("countryNameDomainOnlyMapping","search_companies","companyName","gdmi","businessNameWithNGrams",1.0),                                    
									  ("countryNameDomainOnlyMapping","search_companies","companyName","gdmi","ceoName",1.0),
									  ("countryNameDomainOnlyMapping","search_companies","companyName","gdmi","tradestyle1",1.0),
									  ("countryNameDomainOnlyMapping","search_companies","companyName","former","former1BusinessNameWithStemmer",2.0),
									  ("countryNameDomainOnlyMapping","search_companies","companyName","former","former1BusinessName",2.0),
									  ("countryNameDomainOnlyMapping","search_companies","url","domain_to_duns","url",1.0),
									  ("countryNameDomainOnlyMapping","search_companies","country","gdmi","iso3CountryCode",5.0);
		
update boostconfig set fieldName="iso3CountryCode" where type = "gdmi" and fieldName="countryCode";									
update boostconfigtemplate set fieldName="iso3CountryCode" where type = "gdmi" and fieldName="countryCode";
update secondaryboostconfig set fieldName="iso3CountryCode" where type = "gdmi" and fieldName="countryCode";

insert into secondaryappconfigmappingaccess values (DEFAULT, 1,"z-darwin-default","z-darwin-default.tiers","secondPassMapping","search_companies",true);
insert into secondaryappconfigmappingaccess values (DEFAULT, 1,"z-darwin-default","z-darwin-default.tiers","thirdPassMapping","search_ssr",true);

