CREATE TABLE if not exists stopwords (
  stopword varchar(100) NOT NULL,
  PRIMARY KEY (stopword)
);

create table if not exists stopchars(stopchar char(1) not null,
                       primary key(stopchar));


insert into stopwords values("a");
insert into stopwords values("an");
insert into stopwords values("and");
insert into stopwords values("are");
insert into stopwords values("as");
insert into stopwords values("at");
insert into stopwords values("be");
insert into stopwords values("but");
insert into stopwords values("by");
insert into stopwords values("co");
insert into stopwords values("co.");
insert into stopwords values("corp");
insert into stopwords values("corp.");
insert into stopwords values("corporation");
insert into stopwords values("de");
insert into stopwords values("de.");
insert into stopwords values("for");
insert into stopwords values("holdings");
insert into stopwords values("if");
insert into stopwords values("in");
insert into stopwords values("inc");
insert into stopwords values("inc.");
insert into stopwords values("incorporated");
insert into stopwords values("india private limited");
insert into stopwords values("into");
insert into stopwords values("is");
insert into stopwords values("it");
insert into stopwords values("limited");
insert into stopwords values("limited liability corporation");
insert into stopwords values("llc");
insert into stopwords values("llc.");
insert into stopwords values("ltd");
insert into stopwords values("ltd.");
insert into stopwords values("ltda");
insert into stopwords values("ltda.");
insert into stopwords values("no");
insert into stopwords values("not");
insert into stopwords values("of");
insert into stopwords values("on");
insert into stopwords values("ooo");
insert into stopwords values("or");
insert into stopwords values("partnership");
insert into stopwords values("private");
insert into stopwords values("pvt");
insert into stopwords values("pvt.");
insert into stopwords values("srl");
insert into stopwords values("srl.");
insert into stopwords values("such");
insert into stopwords values("that");
insert into stopwords values("the");
insert into stopwords values("their");
insert into stopwords values("then");
insert into stopwords values("there");
insert into stopwords values("these");
insert into stopwords values("they");
insert into stopwords values("this");
insert into stopwords values("to");
insert into stopwords values("was");
insert into stopwords values("will");
insert into stopwords values("with");
insert into stopwords values("&");
insert into stopwords values("formerly");
insert into stopwords values("dba");
insert into stopwords values("plc");
insert into stopwords values("en");
insert into stopwords values("het");
insert into stopwords values("een");
insert into stopwords values("le");
insert into stopwords values("la");
insert into stopwords values("une");
insert into stopwords values("un");
insert into stopwords values("et");
insert into stopwords values("sprl");
insert into stopwords values("sa");
insert into stopwords values("pa");
insert into stopwords values("btw");
insert into stopwords values("service");
insert into stopwords values("scrl");
insert into stopwords values("bv");
insert into stopwords values("intl");
insert into stopwords values("sprlu");
insert into stopwords values("dhr");
insert into stopwords values("mr");
insert into stopwords values("mevrouw");
insert into stopwords values("mevr");
insert into stopwords values("dr");
insert into stopwords values("madame");
insert into stopwords values("mademoiselle");
insert into stopwords values("monsieur");
insert into stopwords values("ag");
insert into stopwords values("aktien");
insert into stopwords values("aktienges");
insert into stopwords values("aktiengesellschaft");
insert into stopwords values("am");
insert into stopwords values("apotheker");
insert into stopwords values("apothekerin");
insert into stopwords values("auf");
insert into stopwords values("arzt");
insert into stopwords values("cie");
insert into stopwords values("comptoir");
insert into stopwords values("cokg");
insert into stopwords values("das");
insert into stopwords values("den");
insert into stopwords values("der");
insert into stopwords values("des");
insert into stopwords values("die");
insert into stopwords values("dipl");
insert into stopwords values("dritte");
insert into stopwords values("drmed");
insert into stopwords values("el");
insert into stopwords values("fuer");
insert into stopwords values("fur");
insert into stopwords values("gesellschaft");
insert into stopwords values("gesellschaftm");
insert into stopwords values("handelsag");
insert into stopwords values("ihr");
insert into stopwords values("ii");
insert into stopwords values("il");
insert into stopwords values("im");
insert into stopwords values("ingenieure");
insert into stopwords values("ingenieur");
insert into stopwords values("ing");
insert into stopwords values("inhaber");
insert into stopwords values("inhaberin");
insert into stopwords values("inh");
insert into stopwords values("kalte");
insert into stopwords values("maler");
insert into stopwords values("med");
insert into stopwords values("mit");
insert into stopwords values("mme");
insert into stopwords values("ms");
insert into stopwords values("professor");
insert into stopwords values("prof");
insert into stopwords values("sarl");
insert into stopwords values("snc");
insert into stopwords values("stadtbaumeister");
insert into stopwords values("strassen");
insert into stopwords values("strasse");
insert into stopwords values("uer");
insert into stopwords values("und");
insert into stopwords values("unt");
insert into stopwords values("ziviltechniker");
insert into stopwords values("zum");
insert into stopwords values("zur");
insert into stopwords values("zweifel");
insert into stopwords values("gmbh");
insert into stopwords values("mbh");
insert into stopwords values("kgaa");
insert into stopwords values("kg");
insert into stopwords values("ko");
insert into stopwords values("&/or");
insert into stopwords values("/or");
insert into stopwords values("1st");
insert into stopwords values("1v");
insert into stopwords values("2nd");
insert into stopwords values("3r");
insert into stopwords values("3rd");
insert into stopwords values("4th");
insert into stopwords values("accountants");
insert into stopwords values("adm");
insert into stopwords values("admin");
insert into stopwords values("adminis");
insert into stopwords values("administ");
insert into stopwords values("administra");
insert into stopwords values("administr");
insert into stopwords values("administrat");
insert into stopwords values("administrati");
insert into stopwords values("administratio");
insert into stopwords values("administration");
insert into stopwords values("administrativ");
insert into stopwords values("administrative");
insert into stopwords values("administrato");
insert into stopwords values("administrator");
insert into stopwords values("administratr");
insert into stopwords values("administratri");
insert into stopwords values("administratrix");
insert into stopwords values("adminstration");
insert into stopwords values("adminstrator");
insert into stopwords values("admn");
insert into stopwords values("admrx");
insert into stopwords values("admstr");
insert into stopwords values("admstrx");
insert into stopwords values("admx");
insert into stopwords values("all");

insert into stopwords values("aor");
insert into stopwords values("attorneys");
insert into stopwords values("attornies");
insert into stopwords values("australiapty");
insert into stopwords values("benef");
insert into stopwords values("bhd");

insert into stopwords values("cba");

insert into stopwords values("cmp");
insert into stopwords values("cmpny");
insert into stopwords values("cmpy");
insert into stopwords values("co.limited");
insert into stopwords values("coltd");
insert into stopwords values("compa");
insert into stopwords values("compan");
insert into stopwords values("compania");
insert into stopwords values("compani");
insert into stopwords values("companie");
insert into stopwords values("company");
insert into stopwords values("companyinc");
insert into stopwords values("companylimited");
insert into stopwords values("comp");
insert into stopwords values("compny");
insert into stopwords values("conser");
insert into stopwords values("conservator");
insert into stopwords values("conserv");
insert into stopwords values("coordinator");
insert into stopwords values("coporation");
insert into stopwords values("copr");
insert into stopwords values("coproration");
insert into stopwords values("cor");
insert into stopwords values("cordntr");
insert into stopwords values("corpn");
insert into stopwords values("corpo");
insert into stopwords values("corpora");
insert into stopwords values("corporat");
insert into stopwords values("corporate");
insert into stopwords values("corporati");
insert into stopwords values("corporatio");
insert into stopwords values("corporationltd");
insert into stopwords values("corporationsdn");
insert into stopwords values("corpor");
insert into stopwords values("corportion");
insert into stopwords values("corproation");
insert into stopwords values("correspondent");
insert into stopwords values("cpas");
insert into stopwords values("cus");
insert into stopwords values("cust");
insert into stopwords values("custodian");
insert into stopwords values("custody");
insert into stopwords values("dated");
insert into stopwords values("dcd");
insert into stopwords values("decd");
insert into stopwords values("deceased");
insert into stopwords values("ded");
insert into stopwords values("dentists");
insert into stopwords values("dismantler");
insert into stopwords values("dispatcher");
insert into stopwords values("dntlhygnst");
insert into stopwords values("dtd");

insert into stopwords values("estate");
insert into stopwords values("estat");
insert into stopwords values("est");
insert into stopwords values("executor");
insert into stopwords values("exr");
insert into stopwords values("fbo");
insert into stopwords values("fourth");



insert into stopwords values("inco");
insert into stopwords values("incor");
insert into stopwords values("incorp");
insert into stopwords values("incorpo");
insert into stopwords values("incorpora");
insert into stopwords values("incorporate");
insert into stopwords values("incorporat");
insert into stopwords values("incorporation");
insert into stopwords values("incorpor");
insert into stopwords values("iv");
insert into stopwords values("jnr");
insert into stopwords values("jr");
insert into stopwords values("junior");
insert into stopwords values("lim");
insert into stopwords values("limtied");
insert into stopwords values("llp");
insert into stopwords values("lmtd");
insert into stopwords values("lp");
insert into stopwords values("ltdpart");
insert into stopwords values("lwr");
insert into stopwords values("lwyrs");
insert into stopwords values("lyr");

insert into stopwords values("pl");



insert into stopwords values("ass");
insert into stopwords values("asscoates");
insert into stopwords values("assn");
insert into stopwords values("asso");
insert into stopwords values("assoc");
insert into stopwords values("associa");
insert into stopwords values("associ");
insert into stopwords values("associat");
insert into stopwords values("associate");
insert into stopwords values("associated");
insert into stopwords values("associati");
insert into stopwords values("associatio");
insert into stopwords values("association");
insert into stopwords values("assocn");
insert into stopwords values("l l c");
insert into stopwords values("ag co kgaa");
insert into stopwords values("ag co ohg");
insert into stopwords values("ag co");
insert into stopwords values("ggmbh");
insert into stopwords values("gmbh co kg");
insert into stopwords values("gmbh co kgaa");
insert into stopwords values("gmbh co ohg");
insert into stopwords values("gmbh co");
insert into stopwords values("stiftung co kg");
insert into stopwords values("stiftung co");
insert into stopwords values("stiftung");
insert into stopwords values("eg");
insert into stopwords values("ev");
insert into stopwords values("ef");
insert into stopwords values("eu");
insert into stopwords values("se");
insert into stopwords values("ewiv");
insert into stopwords values("gbr");
insert into stopwords values("ohg");
insert into stopwords values("partg");
insert into stopwords values("vvag");
insert into stopwords values("veb");
insert into stopwords values("haftungsbeschrankt");
insert into stopwords values("haftungsbeschraenkt");
insert into stopwords values("kaufmann");
insert into stopwords values("eingetragener");
insert into stopwords values("ek");
insert into stopwords values("ekfm");
insert into stopwords values("ekfr");
insert into stopwords values("cic");
insert into stopwords values("cio");
insert into stopwords values("cyf");
insert into stopwords values("ccc");
insert into stopwords values("untld");
insert into stopwords values("ultd");
insert into stopwords values("pllc");
insert into stopwords values("lllp");
insert into stopwords values("lc");
insert into stopwords values("pc");
insert into stopwords values("partners");
insert into stopwords values ("mgmt");
insert into stopwords values ("store");
insert into stopwords values ("communications");
insert into stopwords values ("consulting");
insert into stopwords values ("industries");
insert into stopwords values ("group");
insert into stopwords values ("properties");
insert into stopwords values ("associates");



insert into stopchars values('-'),
						    ("'"),
							(','),
							('.'),
							('|'),
							('['),
							(']'),
							('('),
							(')'),
							('{'),
							('}');
