create table if not exists display_precedence(id int(11) not null auto_increment,
								name varchar(100),
								primary key(id),
								constraint unique_name unique(name));
								
insert into display_precedence(id, name) values(1,'default');

create table if not exists display_precedence_order(id int(11) not null auto_increment,
									  displayprecedenceid int(11) not null,
									  theorder int(11) not null,
									  thevalue varchar(100),
									  primary key(id),
									  foreign key(displayprecedenceid) references display_precedence(id),
									  constraint unique_precedence unique(displayprecedenceid, thevalue));

insert into display_precedence_order values(1,1,1,'gdmi'),
										   (2,1,2,'former'),
										   (3,1,3,'eha'),
										   (4,1,4,'ssr'),
										   (5,1,5,'gca'),
										   (6,1,6,'domain_to_duns'),
										   (7,1,7,'bus_regstrn'),
										   (8,1,8,'ucc'),
										   (9,1,9,'costco'),
										   (10,1,10,'aon'),
										   (11,1,11,'ibm');
										   
create table if not exists display_mapping(id int(11) not null auto_increment,
									 displayprecedenceid int(11) not null,
									 thetype varchar(100) not null,
									 sourcename varchar(100),
									 displayname varchar(100) not null,
									 lookintype varchar(100),
									 lookintypesourcename varchar(100),
									 primary key(id),
									 foreign key(displayprecedenceid) references display_precedence(id),
									 constraint unique_precedence unique(thetype,sourcename,displayname));	

/*									 
insert into display_mapping values(1,1,'bus_regstrn','','companyName',null,null),
                                  (2,1,'bus_regstrn','','personName',null,null),
                                  (3,1,'bus_regstrn','','email',null,null),
                                  (4,1,'bus_regstrn','','domain',null,null),
                                  (5,1,'bus_regstrn','','url',null,null),
                                  (6,1,'bus_regstrn','','phone',null,null),
                                  (7,1,'bus_regstrn','','phone2',null,null),
                                  (8,1,'bus_regstrn','','nationalIdentifier',null,null),
                                  (9,1,'bus_regstrn','filingAddressStreetAddress','street1',null,null),
                                  (10,1,'bus_regstrn','','street2',null,null),
                                  (11,1,'bus_regstrn','filingAddressCityName','city',null,null),
                                  (12,1,'bus_regstrn','filingAddressStateAbbrName','state',null,null),
                                  (13,1,'bus_regstrn','filingAddressCountryName','country',null,null),
                                  (14,1,'bus_regstrn','filingAddressPostalCode','postalCode',null,null),
                                  (15,1,'gca','businessName','companyName',null,null),
                                  (16,1,'gca','firstName','firstName',null,null),
                                  (17,1,'gca','lastName','lastName',null,null),
                                  (18,1,'gca','streetAddress1','street1',null,null),
                                  (19,1,'gca','cityName','city',null,null),
                                  (20,1,'gca','stateProvinceCode','state',null,null),
                                  (21,1,'gca','countryCode','country',null,null),
                                  (22,1,'gca','postalCode','postalCode',null,null),
                                  (23,1,'gca','primaryPhone','phone',null,null),
                                  (24,1,'gca','emailDomain','domain',null,null),
                                  (25,1,'gdmi','mailAddress1','mailAddress1',null,null),
                                  (26,1,'gdmi','fullMailingAddress','fullMailingAddress',null,null),
                                  (27,1,'gdmi','businessName','companyName',null,null),
                                  (28,1,'gdmi','mailPostalCode','mailPostalCode',null,null),
                                  (29,1,'gdmi','mailPostalCode5','mailPostalCode5',null,null),
                                  (30,1,'gdmi','mailStateAbbreviation','mailStateAbbreviation',null,null),
                                  (31,1,'gdmi','mailCityName','mailCityName',null,null),                                                                   
                                  (34,1,'gdmi','','domain','domain_to_duns','rawDomain'),
                                  (35,1,'gdmi','','businessNames','former','businessNames'),
                                  (36,1,'gdmi','','tradestyles','former','tradestyles'),
                                  (37,1,'gdmi','','url',null,null),
                                  (38,1,'gdmi','telephoneNumber','phone',null,null),
                                  (39,1,'gdmi','fullAddress','fullAddress',null,null),
                                  (40,1,'gdmi','address1','street1',null,null),
                                  (41,1,'gdmi','address2','street2',null,null),
                                  (42,1,'gdmi','ceoName','CEOName',null,null),
                                  (43,1,'gdmi','tradestyle1','tradestyle1',null,null),
                                  (44,1,'gdmi','','phone2',null,null),
                                  (45,1,'gdmi','nationalIdentifier','nationalIdentifier',null,null),
                                  (46,1,'gdmi','city','city',null,null),
                                  (47,1,'gdmi','stateAbbreviation','state',null,null),
                                  (48,1,'gdmi','countryCode','country',null,null),
                                  (49,1,'gdmi','postalCode','postalCode',null,null),
                                  (50,1,'gdmi','fullAddress','physicalAddress',null,null),
                                  (51,1,'gdmi','locationType','locationType',null,null),
                                  (52,1,'gdmi','outOfBusinessIndicator','outOfBusinessIndicator',null,null),
                                  (53,1,'gdmi','lastUpdateDate','lastUpdateDate',null,null),
                                  (54,1,'gdmi','','fullPrimaryAddress','ssr','fullPrimaryAddress'),
                                  (55,1,'gdmi','','physicalStreetAddressLine','ssr','physicalStreetAddressLine'),
                                  (56,1,'gdmi','','physicalPostalCode','ssr','physicalPostalCode'),
                                  (57,1,'gdmi','','mailCountryCode','ssr','mailCountryCode'),
                                  (58,1,'gdmi','','physicalPrimaryTownCityName','ssr','physicalPrimaryTownCityName'),
                                  (59,1,'gdmi','','mailStreetAddressLineText','ssr','mailStreetAddressLineText'),
                                  (60,1,'gdmi','','mailPrimaryTownCityName','ssr','mailPrimaryTownCityName'),
                                  (61,1,'gdmi','','mailPostalCode','ssr','mailPostalCode'),
                                  (62,1,'gdmi','','mailTerritoryName','ssr','mailTerritoryName'),
                                  (64,1,'gdmi','','fullMailingAddress','ssr','fullMailingAddress'),
                                  (65,1,'gdmi','','mailStreetAddressLine4Text','ssr','mailStreetAddressLine4Text'),
                                  (66,1,'gdmi','','former1BusinessName','former','former1BusinessName'),
                                  (67,1,'gdmi','','former2BusinessName','former','former2BusinessName'),
                                  (68,1,'gdmi','','former3BusinessName','former','former3BusinessName'),
                                  (69,1,'gdmi','','former1FullAddress','former','former1FullAddress'),
                                  (70,1,'gdmi','','former2FullAddress','former','former2FullAddress'),
                                  (71,1,'gdmi','','former3FullAddress','former','former3FullAddress'),
                                  (72,1,'gdmi','','former1FullMailingAddress','former','former1FullMailingAddress'),
                                  (73,1,'gdmi','','former2FullMailingAddress','former','former2FullMailingAddress'),
                                  (74,1,'gdmi','','former3FullMailingAddress','former','former3FullMailingAddress'),
                                  (75,1,'gdmi','','former1City','former','former1City'),
                                  (76,1,'gdmi','','former2City','former','former2City'),
                                  (77,1,'gdmi','','former3City','former','former3City'),
                                  (78,1,'gdmi','','former1MailCity','former','former1MailCity'),
                                  (79,1,'gdmi','','former2MailCity','former','former2MailCity'),
                                  (80,1,'gdmi','','former3MailCity','former','former3MailCity'),
                                  (81,1,'gdmi','','former1State','former','former1State'),
                                  (82,1,'gdmi','','former2State','former','former2State'),
                                  (83,1,'gdmi','','former3State','former','former3State'),
                                  (84,1,'gdmi','','former1MailState','former','former1MailState'),
                                  (85,1,'gdmi','','former2MailState','former','former2MailState'),
                                  (86,1,'gdmi','','former3MailState','former','former3MailState'),
                                  (87,1,'gdmi','','former1PostalCode','former','former1PostalCode'),
                                  (88,1,'gdmi','','former2PostalCode','former','former2PostalCode'),
                                  (89,1,'gdmi','','former3PostalCode','former','former3PostalCode'),
                                  (90,1,'gdmi','','former1MailPostalCode','former','former1MailPostalCode'),
                                  (91,1,'gdmi','','former2MailPostalCode','former','former2MailPostalCode'),
                                  (92,1,'gdmi','','former3MailPostalCode','former','former3MailPostalCode'),
                                  (93,1,'gdmi','','former1Street1','former','former1Street1'),
                                  (94,1,'gdmi','','former2Street1','former','former2Street1'),
                                  (95,1,'gdmi','','former3Street1','former','former3Street1'),
                                  (96,1,'gdmi','','former1MailStreet1','former','former1MailStreet1'),
                                  (97,1,'gdmi','','former2MailStreet1','former','former2MailStreet1'),
                                  (98,1,'gdmi','','former3MailStreet1','former','former3MailStreet1'),
                                  (99,1,'gdmi','','former1TelephoneNumber','former','former1TelephoneNumber'),
                                  (100,1,'gdmi','','former2TelephoneNumber','former','former2TelephoneNumber'),
                                  (101,1,'gdmi','','former3TelephoneNumber','former','former3TelephoneNumber'),
                                  (102,1,'gdmi','','formerBusinessNames','former','formerBusinessNames'),
                                  (103,1,'gdmi','','fullHomeAddress','eha','fullHomeAddress'),
                                  (104,1,'gdmi','','fullHomeAddress5','eha','fullHomeAddress5'),
                                  (105,1,'gdmi','','homeZipCode','eha','homeZipCode'),
                                  (106,1,'gdmi','','homeZipCode5','eha','homeZipCode5'),
                                  (107,1,'gdmi','','homeState','eha','homeState'),
                                  (108,1,'gdmi','','homeCity','eha','homeCity'),
                                  (109,1,'gdmi','','homeAddress','eha','homeAddress'),
                                  (110,1,'gdmi','','executiveName','eha','fullName'),
                                  

                                  (111,1,'gdmi','globalUltimateDuns','globalUltimateDuns',null,null),
                                  (112,1,'gdmi','domesticUltimateDuns','globalUltimateDuns',null,null),
                                  
                                  (113,1,'eha','fullHomeAddress','fullHomeAddress',null,null),
                                  (114,1,'eha','fullHomeAddress5','fullHomeAddress5',null,null),
                                  (115,1,'eha','homeZipCode5','homeZipCode5',null,null),
                                  (116,1,'eha','homeZipCode','homeZipCode',null,null),
                                  (117,1,'eha','homeState','homeState',null,null),
                                  (118,1,'eha','homeCity','homeCity',null,null),
                                  (119,1,'eha','homeAddress','homeAddress',null,null),                                  
                                  (120,1,'eha','fullName','fullName',null,null),
                                  (123,1,'former','former1BusinessName','former1BusinessName',null,null),
                                  (124,1,'former','former2BusinessName','former2BusinessName',null,null),
                                  (125,1,'former','former3BusinessName','former3BusinessName',null,null),
                                  (126,1,'former','former1TelephoneNumber','former1TelephoneNumber',null,null),
                                  (127,1,'former','former2TelephoneNumber','former2TelephoneNumber',null,null),
                                  (128,1,'former','former3TelephoneNumber','former3TelephoneNumber',null,null),
                                  (129,1,'former','former1FullAddress','former1FullAddress',null,null),
                                  (130,1,'former','former2FullAddress','former2FullAddress',null,null),
                                  (131,1,'former','former3FullAddress','former3FullAddress',null,null),
                                  (132,1,'former','former1FullMailingAddress','former1FullMailingAddress',null,null),
                                  (133,1,'former','former2FullMailingAddress','former2FullMailingAddress',null,null),
                                  (225,1,'former','former3FullMailingAddress','former3FullMailingAddress',null,null),
                                  (134,1,'former','former1City','former1City',null,null),
                                  (135,1,'former','former2City','former2City',null,null),
                                  (136,1,'former','former3City','former3City',null,null),
                                  (137,1,'former','former1MailCity','former1MailCity',null,null),
                                  (138,1,'former','former2MailCity','former2MailCity',null,null),
                                  (139,1,'former','former3MailCity','former3MailCity',null,null),
                                  (140,1,'former','former1State','former1State',null,null),
                                  (141,1,'former','former2State','former2State',null,null),
                                  (142,1,'former','former3State','former3State',null,null),
                                  (143,1,'former','former1MailState','former1MailState',null,null),
                                  (144,1,'former','former2MailState','former2MailState',null,null),
                                  (145,1,'former','former3MailState','former3MailState',null,null),
                                  (146,1,'former','former1Street1','former1Street1',null,null),
                                  (147,1,'former','former2Street1','former2Street1',null,null),
                                  (148,1,'former','former3Street1','former3Street1',null,null),
                                  (149,1,'former','former1MailingStreet1','former1MailingStreet1',null,null),
                                  (150,1,'former','former2MailingStreet1','former2MailingStreet1',null,null),
                                  (151,1,'former','former3MailingStreet1','former3MailingStreet1',null,null),
                                  (152,1,'former','former1MailPostalCode','former1MailPostalCode',null,null),
                                  (153,1,'former','former2MailPostalCode','former2MailPostalCode',null,null),
                                  (154,1,'former','former3MailPostalCode','former3MailPostalCode',null,null),
                                  (155,1,'former','former1PostalCode','former1PostalCode',null,null),
                                  (156,1,'former','former2PostalCode','former2PostalCode',null,null),
                                  (157,1,'former','former3PostalCode','former3PostalCode',null,null),
                                  (158,1,'gds','worldbase_outOfBusinessFlag','outOfBusinessIndicator',null,null),
                                  (159,1,'gds','worldbase_businessName','companyName',null,null),
                                  (160,1,'gds','','personName',null,null),
                                  (161,1,'gds','','email',null,null),
                                  (162,1,'gds','','domain','domain_to_duns','rawDomain'),
                                  (163,1,'gds','','url',null,null),
                                  (164,1,'gds','worldbase_telephoneNumber','phone',null,null),
                                  (165,1,'gds','GDS_fullPostalAddress','fullAddress',null,null),
                                  (166,1,'gds','worldbase_CEOName','CEOName',null,null),
                                  (167,1,'gds','worldbase_tradeStyleName','tradeStyleName',null,null),
                                  (168,1,'gds','worldbase_faxNumber','phone2',null,null),
                                  (169,1,'gds','worldbase_national_id','nationalIdentifier',null,null),
                                  (170,1,'gds','worldbase_cityName','city',null,null),
                                  (171,1,'gds','worldbase_stateProvinceName','state',null,null),
                                  (172,1,'gds','worldbase_countryCode','country',null,null),
                                  (173,1,'gds','zip5','postalCode',null,null),
                                  (174,1,'gds','worldbase_physicalAddress','physicalAddress',null,null),
                                  (175,1,'gds','worldbase_locationType','locationType',null,null),
                                  (176,1,'domain_to_duns','','companyName',null,null),
                                  (177,1,'domain_to_duns','','personName',null,null),
                                  (178,1,'domain_to_duns','','email',null,null),
                                  (179,1,'domain_to_duns','rawDomain','domain',null,null),
                                  (180,1,'domain_to_duns','url','url',null,null),
                                  (181,1,'domain_to_duns','','phone',null,null),
                                  (182,1,'domain_to_duns','','phone2',null,null),
                                  (183,1,'domain_to_duns','','nationalIdentifier',null,null),
                                  (184,1,'domain_to_duns','','street1',null,null),
                                  (185,1,'domain_to_duns','','street2',null,null),
                                  (186,1,'domain_to_duns','','city',null,null),
                                  (187,1,'domain_to_duns','','state',null,null),
                                  (188,1,'domain_to_duns','','country',null,null),
                                  (189,1,'domain_to_duns','','postalCode',null,null),
                                  (190,1,'ssr','duns','duns',null,null),
                                  (191,1,'ssr','businessName','companyName',null,null),
                                  (192,1,'ssr','seniorPrincipalName','personName',null,null),
                                  (194,1,'ssr','contactNameEmailAddress','email',null,null),
                                  (195,1,'ssr','businessURL','url',null,null),
                                  (196,1,'ssr','telephoneNumber','phone',null,null),
                                  (197,1,'ssr','physicalPrimaryTownCityName','city',null,null),
                                  (198,1,'ssr','physicalTerritoryName','state',null,null),
                                  (199,1,'ssr','physicalPostalCode','postalCode',null,null),
                                  (200,1,'ssr','physicalStreetAddressLine','street1',null,null),
                                  (201,1,'ssr','fullPrimaryAddress','fullAddress',null,null),
                                  (202,1,'ssr','fullMailingAddress','fullMailingAddress',null,null),
                                  (203,1,'ssr','mailStreetAddressLineText','mailStreetAddressLineText',null,null),
                                  (204,1,'ssr','mailPrimaryTownCityName','mailPrimaryTownCityName',null,null),
                                  (205,1,'ssr','mailPostalCode','mailPostalCode',null,null),
                                  (206,1,'ssr','mailTerritoryName','mailTerritoryName',null,null),
                                  (207,1,'ssr','mailCountryCode','mailCountryCode',null,null),
                                  (208,1,'ssr','mailStreetAddressLine4Text','mailStreetAddressLine4Text',null,null),
                                  (209,1,'ucc','filingName','companyName',null,null),
                                  (210,1,'ucc','businessDunsNumber','duns',null,null),
                                  (211,1,'ucc','businessEntityId','businessEntityId',null,null),
                                  (212,1,'ucc','','email',null,null),
                                  (213,1,'ucc','','domain',null,null),
                                  (214,1,'ucc','','url',null,null),
                                  (215,1,'ucc','','phone',null,null),
                                  (216,1,'ucc','','phone2',null,null),
                                  (217,1,'ucc','entityId','nationalIdentifier',null,null),
                                  (218,1,'ucc','filingAddressStreetAddress','street1',null,null),
                                  (219,1,'ucc','','street2',null,null),
                                  (220,1,'ucc','filingAddressCityName','city',null,null),
                                  (221,1,'ucc','filingAddressStateAbbreviationName','state',null,null),
                                  (222,1,'ucc','filingAddressCountryName','country',null,null),
                                  (223,1,'ucc','filingAddressPostalCode','postalCode',null,null),
                                  (224,1,'gdmi','sics','sics',null,null),	
                                  (226,1,'gdmi','stateProvinceName','stateName',null,null),
								*/
								/*Start of Costco display_mapping */
                                  /*
                                  
                                  (227,1,'costco','costco_businessName','costco_companyName',null,null),
                                  (228,1,'costco','costco_firstName','costco_firstName',null,null),
                                  (229,1,'costco','costco_lastName','costco_lastName',null,null),
                                  (230,1,'costco','costco_telephone1','costco_telephone1',null,null),
                                  (231,1,'costco','fullAddress','fullAddress',null,null),
                                  (232,1,'costco','fullMailingAddress','fullMailingAddress',null,null),
                                  (233,1,'costco','costco_city','costco_city',null,null),
                                  (234,1,'costco','city','city',null,null),
                                  (235,1,'costco','mailCity','mailCity',null,null),
                                  (236,1,'costco','costco_state','costco_state',null,null),
                                  (237,1,'costco','stateAbbreviation','state',null,null),
                                  (238,1,'costco','postalCode','postalCode',null,null),
                                  (239,1,'costco','costco_postalCode','costco_postalCode',null,null),
                                  (240,1,'costco','mailPostalCode','mailPostalCode',null,null),
                                  (241,1,'costco','postalCode5','postalCode5',null,null),
                                  (242,1,'costco','mailPostalCode5','mailPostalCode5',null,null),
                                  (243,1,'costco','costco_address1','costco_address1',null,null),
                                  (244,1,'costco','costco_postaCode4','costco_postaCode4',null,null),
                                  (245,1,'costco','costco_telephone2','costco_telephone2',null,null),
                                  (246,1,'costco','businessName','companyName',null,null),
                                */  
                                /*End of Costco display_mapping*/
                                  /*
                                  (247,1,'gdmi','','fullAddress','gca','fullPostalAddress'),
                                  (248,1,'gdmi','','city','gca','cityName'),
                                  (249,1,'gdmi','','email','gca','email'),
                                  (250,1,'gdmi','','emailDomain','gca','emailDomain'),
                                  (251,1,'gdmi','','country','gca','countryCode'),
                                  (252,1,'gdmi','','emailUrl','gca','emailDomain'),
                                  (253,1,'gdmi','','personName','gca','fullName'),
                                  (254,1,'gca','email','email',null,null),
                                  (255,1,'gca','fullPostalAddress','fullAddress',null,null),
                                  (256,1,'gdmi','tradestyle2','tradestyle2',null,null),
                                  (257,1,'gdmi','tradestyle3','tradestyle3',null,null),
                                  (258,1,'gdmi','tradestyle4','tradestyle4',null,null),
                                  (259,1,'gdmi','tradestyle5','tradestyle5',null,null),
                                  
                                  (260, 1, 'ibm', 'postalCode', 'postalCode',null,null),
								  (261, 1, 'ibm', 'postalCode5', 'postalCode5',null,null),
								  (262, 1, 'ibm', 'address1', 'address1',null,null),
								  (263, 1, 'ibm', 'fullAddress5', 'fullAddress5',null,null),
								  (264, 1, 'ibm', 'fullAddress', 'fullAddress',null,null),
								  (265, 1, 'ibm', 'stateAbbreviation', 'state',null,null),
								  (266, 1, 'ibm', 'businessName', 'companyName',null,null),
								  (267, 1, 'ibm', 'countryName', 'country',null,null),
								  (268, 1, 'ibm', 'duns', 'duns',null,null);
*/
